### ISSUE TITLE
Scriptable AQI does not match URL AQI

### ISSUE THREAD

**Issue by Isaac-Tait** [jasonsnell/PurpleAir-AQI-Scriptable-Widget#1]
First let me say thank you for the great work on this service! 

I set my sensor to 49237 (Fallbrook, CA) and the URL shows 70 but the Scriptable App shows 53... 

If I switch to 60181 (Oceanside, CA) the URL shows 70 but the Scriptable App shows 48...

Is anyone else experiencing this dichotomy in reported numbers?

**Comment by jasonsnell** [comment]
Isaac,

This widget is using a new EPA calculation for smoke from wildfires to be
used by low-cost sensors like PurpleAir.

PurpleAir has not yet updated its own stats to support this calculation,
though if you switch the conversion setting on the PurpleAir map to
"AQandU" you will get closer. That's another calculation that does a better
job.

EPA seems to suggest that PurpleAir is going to add this calculation in the
future, but it's in this widget now.

**Comment by jasonsnell** [comment]
More info is in the README file at the top level of this project, including a couple of links. Thanks for the question @Isaac-Tait!

**Comment by Isaac-Tait** [comment]
Thank you for the prompt and thorough reply 💯
