### ISSUE TITLE
Reference Error

### ISSUE THREAD

**Issue by carlymy** [jasonsnell/PurpleAir-AQI-Scriptable-Widget#12]
Hi! Thank you so much for creating this code. As a Bay Area resident, it is so helpful!

I’m getting the following error message when I run the script:

ReferenceError: Can't find variable: createSymbol

Help?

![35AE26EB-868A-4C81-9BE8-660180D24D3E](https://user-images.githubusercontent.com/72609433/95581039-26ee9080-09ed-11eb-889e-f81ac850c731.jpeg)

**Comment by a-ogilvie** [comment]
@carlymy `createSymbol` is the name of a function that is used to generate a symbol that represents the recent air quality trend.

Are you sure you copy+pasted the entire script correctly? Perhaps you missed the part that contains `createSymbol`.

**Comment by carlymy** [comment]
I missed `function createSymbol` at the bottom ... *facepalm*

Thanks for the help!
