### ISSUE TITLE
Dark mode doesn't work right

### ISSUE THREAD

**Issue by jasonsnell** [jasonsnell/PurpleAir-AQI-Scriptable-Widget#18]
I'm not sure what can be done about this. Something is not getting through to the widget from Scriptable or the system.

If there's no good resolution I am tempted to rip out dark mode support or at least force one mode for the time being.

**Comment by eventualbuddha** [comment]
I've noticed this too. I assumed it was cached and that the next refresh would be right. Has that been the case for you?

**Comment by jasonsnell** [comment]
I'm disabling it for now because it just doesn't work consistently. I think either Scriptable or the system is just not allowing the widget to refresh the color scheme?

**Comment by lickel** [comment]
I had exchanged emails with the developer about supporting "dynamic" colors (how UIKit deals with this).
I'm not 100% sure it can be done with the current SwiftUI APIs, but that's how I expect it would be fixed.

You'd basically do something _like_ `let dynamic = Color({ light: someColor, dark: someColor })`

**Comment by jasonsnell** [comment]
Woo! Resolved in latest version. @lickel
