### ISSUE TITLE
Error message - “correct format”

### ISSUE THREAD

**Issue by satyangajwani** [jasonsnell/PurpleAir-AQI-Scriptable-Widget#19]
I get this error message sometimes. Not sure what causes it. Same code works 80% of the tome, but 20% gives me this error. 
![2D0FD19C-D35B-4F4B-8806-51D21759875B](https://user-images.githubusercontent.com/62442776/95935679-a7fcad80-0d88-11eb-8851-ad66674ca1a6.jpeg)

**Comment by jasonsnell** [comment]
This is due to PurpleAir rejecting the request. The newest version has some code to make this error prettier. We should probably investigate just caching the most recent sensor data and using it in case of error.
