### ISSUE TITLE
Support new purpleair API

### ISSUE THREAD

**Issue by jasonsnell** [jasonsnell/PurpleAir-AQI-Scriptable-Widget#32]
The API this widget uses has been shut down by PurpleAir. It won't work until it's rewritten to use the new API.

**Comment by jasonsnell** [comment]
Did some work on this today. The API is very straightforward. However, this widget has been built to also use PurpleAir for geolocation and I'm not sure that's supported anymore. I'm going to have to dig in a lot deeper to see if I can figure out how to adjust this to use the new API, because there's a lot of code I didn't write in here....

**Comment by jasonsnell** [comment]
Posted a (probably buggy) version in the [new-api ](https://github.com/jasonsnell/PurpleAir-AQI-Scriptable-Widget/tree/new-api) branch.

**Comment by lickel** [comment]
If you create a pull request from that branch, I could add review comments to help you with some of the other bits.
Alternatively, I could make a PR off of your branch. What would you prefer?
I just put in my request for an API key. No idea about the turnaround time.

Incidentally, I got lucky with when they cut over. Only a month ago, I was in Santa Fe, surrounded by wildfires.

Most of the geolocation stuff was just using Apple's APIs.
Looking at the API doc, I _think_ you could use the geolocation data with the [/sensors](https://api.purpleair.com/#api-sensors-get-sensors-data) list api. 
You would then use that haversine() function to find the closest location from the list.

**Comment by jasonsnell** [comment]
@lickel In getting it running I ripped stuff out that probably should go back. I was going to look at that today since I've got a functional api key

**Comment by jasonsnell** [comment]
@lickel Okay, it's in at #33  as a pull request. The issue that remains is parsing the results in getSensorId - I just don't understand the method being used there to parse the new JSON format. If you could look at that, I think we could restore all functionality to this (other than requiring an API key).

For the record, here's what the API spits back for a sample query:

{"data_time_stamp":1653859620,"max_age":3600,"fields":["sensor_index","name","latitude","longitude","location_type"],"data":[[133357,"Stinson Beach",37.901739999999997,-122.65018999999999,0],[4793,"Buckeye Circle",37.998215000000002,-122.63343999999999,0],[13143,"120 pine ave",38.006317000000003,-122.630646,0],[15251,"Woodacre upper Redwood",37.999096000000002,-122.63537599999999,0],[22509,"Forest Dr",38.013165000000001,-122.68608999999999,0],[28965,"Lucas Valley",38.053049999999999,-122.658745,0],[33629,"Nicasio Volunteer Fire Department",38.062260000000002,-122.69800600000001,0],[38459,"Horseshoe Hill",37.930396999999999,-122.69982,0],[50431,"Morelos Ave",38.014519999999997,-122.691345,0],[53661,"Nicasio Valley Road",38.042763000000001,-122.68407000000001,0],[54121,"Wharf Road, Bolinas",37.909443000000003,-122.68216,0],[54897,"fritz",37.904890000000002,-122.68822,0],[58855,"Stinson Beach",37.901764,-122.65004,0],[59703,"Bo",37.901755999999999,-122.70577,0],[60135,"ORR",38.071728,-122.6546,0],[60501,"Point Reyes Mesa bluff",38.079253999999999,-122.81699,0],[65427,"6301",38.074809999999999,-122.72319,0],[66397,"Meadow Lane",38.105034000000003,-122.64286,0],[67383,"3 Nicasio creek rd",38.056457999999999,-122.70583000000001,0],[67405,"Stinson Highlands",37.904076000000003,-122.64167,0],[68321,"Camp Lagunitas",38.017173999999997,-122.69758,0],[69369,"Tamal Road",38.018805999999998,-122.69163500000001,0],[70609,"Spirit Rock Meditation Center",38.018604000000003,-122.64403,0],[71439,"Sir Francis Drake & Balboa Avenue",38.063006999999999,-122.82042,0],[75199,"Rancho Santa Margarita",38.036503000000003,-122.64921,0],[75205,"Bolinas",37.905464000000002,-122.68767,0],[81383,"Olema",38.039805999999999,-122.78698,0],[87089,"Silver Hills, Point Reyes Station",38.060364,-122.81967,0],[100255,"Kale",37.898710000000001,-122.7016,0],[102530,"300s Seadrift Rd",37.907364000000001,-122.67364499999999,0],[104692,"Casa Manana",38.071506999999997,-122.80678,0],[110414,"Woodacre lower flats",38.012034999999997,-122.64381400000001,0],[113801,"Bear Valley Visitor Center",38.04128,-122.80031,0],[117425,"Stinson Beach Seadrift",37.907513000000002,-122.67127000000001,0],[120735,"Indian Hill",38.072823,-122.7486,0]],"location_types":["outside","inside"],"api_version":"V1.0.10-0.0.17","time_stamp":1653859653,"location_type":0,"firmware_default_version":"7.00"}

**Comment by jasonsnell** [comment]
I should mention, as of right now I'm making that API request with a limitation to outdoor sensors that have reported data in the last hour... which seems about right for this use.
