### ISSUE TITLE
Location issue

### ISSUE THREAD

**Issue by sfksuperman** [jasonsnell/PurpleAir-AQI-Scriptable-Widget#35]
While running it, says **Please specify a location for this widget**.

Can you please guide at which line I need to enter the location details?

**Comment by jasonsnell** [comment]
The Widget is supposed to find the nearest PA station to your location via location services. If that's not working, you can specify a PA manually by tapping and holding on the widget, choosing Edit Widget, and then editing the PurpleAir ID of the station you want to monitor in the Parameter field.

**Comment by sfksuperman** [comment]
Yeah got it, thanks.
But one issue with it is the location is confined till American continent only.
Can you not make an alternate script that it calculates Air Quality pf my nearby location worldwide? I can provide you some good websites if you want.

**Comment by jasonsnell** [comment]
Sorry, that's beyond the scope of my project. You are welcome to fork this and adapt it if you like. Or look for apps that support air quality in other regions.

**Comment by jasonsnell** [comment]
Sorry, that's beyond my scope. You are welcome to fork this and adapt it if you like. 

-jason
(from my phone)
