### ISSUE TITLE
Cannot specify indoor sensors

### ISSUE THREAD

**Issue by mewriko** [jasonsnell/PurpleAir-AQI-Scriptable-Widget#36]
Tried to specify a specific sensor with Param and got a "Couldn't connect to the server." error message. After poking around I figured out that the script only works for outdoor sensors. I want a widget that shows my indoor sensor. 

Tried changing location_type to 1 but this did not fix it. Any leads?

**Comment by jasonsnell** [comment]
This is because I'm not properly detecting the lack of a second sensor on an indoor sensor. I'll look into this, it should be pretty straightforward to fix.

**Comment by jasonsnell** [comment]
Ok, I think this is fixed in the latest push to main. Please give it a try.
