### ISSUE TITLE
listWidget.addStack is not a function 

### ISSUE THREAD

**Issue by oddetc** [jasonsnell/PurpleAir-AQI-Scriptable-Widget#5]
Looks like the change pushed around an hour ago broke the script. I don’t see .addStack in the Scriptable documentation for a ListWidget either.

![F6CF59B5-B8D2-4EFE-9A84-C01D36090EFB](https://user-images.githubusercontent.com/3693123/94981320-21bdad00-04e6-11eb-84bb-627dcd0f6ca0.jpeg)

**Comment by jasonsnell** [comment]
Sorry, I need to start doing branches for features added during Scriptable betas. I'll do that once this version ships.

In the meantime, sign up for the Scriptable beta: https://testflight.apple.com/join/klHcZHjN

**Comment by jasonsnell** [comment]
@oddetc BTW, if you don't want to sign up for the beta just look in the repository history and grab an older version!

**Comment by oddetc** [comment]
Unfortunately the beta is full, but I did grab an older working version. Thanks for the quick reply and the awesome widget script!

**Comment by eventualbuddha** [comment]
@oddetc the main branch should work with the App Store again. I submitted a fix to work with both versions in #6.
