### ISSUE TITLE
Set default station using location data

### ISSUE THREAD

**Issue by jasonsnell** [jasonsnell/PurpleAir-AQI-Scriptable-Widget#8]
I would like to remove the dummy "default station ID" and have the widget work automatically with the nearest PurpleAir station when possible.

Here's what I've got so far, but I need someone's help to extract the closest station and my skills are not close to being able to do this.

I've got a function that will calculate a distance based on lat and long but I have no idea how to sort through all the returned items to detect the one that's closest.

If anyone has suggestions I'd love to hear it! @a-ogilvie 

```
let loc = await Location.current()    
// Now we can use the location. If Location.current() fails, exection
// of the script will terminate and an error is shown in the log.
let lat = loc["latitude"]
let lon = loc["longitude"]

let nwLat = round( (lat + .003 ) , 4)
let seLat = round( (lat - .003 ) , 4)
let nwLng = round( (lon - .003 ) , 4)
let seLng = round( (lon + .003 ) , 4)

let req = new Request("https://www.purpleair.com/data.json?opt=1/mAQI/a10/cC5&fetch=true&nwlat=" + nwLat + "&selat=" + seLat + "&nwlng=" + nwLng + "&selng=" + seLng + "&fields=pm_1,pm_cf_1,humidity")

let json = await req.loadJSON()

let stats = json.data[0]

let labelIndex = json.fields.indexOf("Label");
let latIndex = json.fields.indexOf("Lat");
let lonIndex = json.fields.indexOf("Lon");
let stationIndex = json.fields.indexOf("ID");

json.data.forEach(item => {

let thisDistance = (distance (lat, lon, item[latIndex], item[lonIndex], 'K') ) 

console.log (thisDistance);

// console.log (`${item[labelIndex]}` + ' ' + (distance (lat, lon, item[latIndex], item[lonIndex], 'K') ) );

});


function round(value, decimals) {
  return Number(Math.round(value+'e'+decimals)+'e-'+decimals);
}

function distance(lat1, lon1, lat2, lon2, unit) {
    var radlat1 = Math.PI * lat1/180
    var radlat2 = Math.PI * lat2/180
    var theta = lon1-lon2
    var radtheta = Math.PI * theta/180
    var dist = Math.sin(radlat1) * Math.sin(radlat2) + Math.cos(radlat1) * Math.cos(radlat2) * Math.cos(radtheta);
    if (dist > 1) {
        dist = 1;
    }
    dist = Math.acos(dist)
    dist = dist * 180/Math.PI
    dist = dist * 60 * 1.1515
    if (unit=="K") { dist = dist * 1.609344 }
    if (unit=="N") { dist = dist * 0.8684 }
    return dist
}

```

**Comment by lickel** [comment]
I haven't personally written sorting code in javascript, but I know the old level attributes stuff worked via sorting.

```js
// Get level attributes for AQI
function getLevelAttributes(level, attributes) {
  let applicableAttributes = attributes
    .filter((c) => level > c.threshold)
    .sort((a, b) => b.threshold - a.threshold);
  return applicableAttributes[0];
}
```

### Prepare

To avoid this taking forever, you should add the distance to each item.
You could do something like:

```js
const weightedItems = json.data.map(item => {
    const distance = distance (lat, lon, item[latIndex], item[lonIndex], 'K');
    return {
        distance,
        ...item,
    }
});
```


### Get your item

This will sort it and then get the first element. I *think* this will get you the correct element.
If I'm wrong, the first element will be the furthest element 😉.
If that's the case, you can just flip the math to `b.distance - a.distance`.

```js
let desiredItem = weightedItems.sort((a, b) => a.distance - b.distance)[0];
```

**Comment by eventualbuddha** [comment]
I can do this, but I have a few questions: do you want any sensor or only outdoor? what happens if there are no sensors in the area? should it expand the search area? default to a "demo" sensor as before or show a "nothing nearby" screen?

**Comment by jasonsnell** [comment]
I created the location branch for this stuff.

I think ideally the widget would look and find the nearest sensor, within reason, but if there's nothing it should just go back to a demo sensor.

**Comment by jasonsnell** [comment]
Also thanks to both of you for contributing to this, it's awesome!

**Comment by jasonsnell** [comment]
#11 is looking really great @a-ogilvie @lickel @eventualbuddha !! Amazing. And I am learning some nice JavaScript tricks while watching this. It's so frustrating to know the method to use to approach a problem but not know the idiom of the language. And I definitely learn by example.

I was going to live with this for a day or two before considering a push into the main branch. Are there any issues with this approach that anyone is concerned about? 

I am considering some way in the widget display to indicate that location is being used to infer a station, but I'm not sure it's necessary....

**Comment by jasonsnell** [comment]
Hmm, I'm seeing some issues with location finding, I wonder if it can be handled by the script or if it might be a Scriptable issue.

I just woke up my iPad and got a white widget that said "your location can't be determined." A few minutes later it was replaced by 1080 Bear Gulch, the demo station ID.

1 - I wonder if we can't determine a location if, rather than showing a demo station, the widget should just put up a warning that the user should set a location?

2 - Is there a way to better handle location with relation to Scriptable? (I might ask Simon about this.)

**Comment by lickel** [comment]
If I had to guess, the widget needs “always” location permissions to work. Is that what Scriptable has for you?

**Comment by jasonsnell** [comment]
I've got "While Using the App or Widgets" set, which is the most permissive level available to me in the Location Services settings view.

**Comment by lickel** [comment]
OK, looks like Simon explicitly has not requested “always” permissions (understandably). 

> Access Location Information From Your Widget
> 
>  When the user adds a widget that uses location, the system asks whether they want to extend the app’s location authorization to the widget. Use authorizedForWidgetUpdates to determine whether the widget is eligible to receive location updates. Users can change their approval choice at any time in Settings > Privacy > Location Services.
After the user approves the widget’s use of location information, the system considers it “in use” for a short period of time after the widget is visible. If the system refreshes the widget’s view during this in-use period, the widget has access to location information. For example, immediately after a user adds a widget to their home screen and approves extending the app’s location authorization, the user’s location is available to the widget.
When the widget hasn’t been visible for a period of time, the system no longer considers it in use and stops delivering location updates. When WidgetKit reloads the widget’s view, if authorizedForWidgetUpdates is true but the widget doesn’t get location updates, it’s a good practice to indicate that the user’s location is not currently available. Note, this is different from when authorizedForWidgetUpdates is false, which indicates that the user has not approved the widget to receive location updates.

Source: [Apple Developer Site](https://developer.apple.com/documentation/corelocation/requesting_authorization_for_location_services)

---

I think the only way this can work is if we cache the location, or we use this as a helpful step when `config.runsInApp `. Caching the location isn’t bad, as long as the expectation is that this _potentially_ won’t ever update the location. 

We can use the [FileManager](https://docs.scriptable.app/filemanager/) APIs to save the location. Basically using `FileManager.local().libraryDirectory()` to read/write some JSON off.

Given how the framework is built, and the location restrictions we have, it’s probably safe to just always request your location, as long as we catch the error.

I can take a crack at it this weekend (unless you’re itching to write more js). 

---

I can totally sympathize with knowing how to conceptually do something, but be hindered by the language. Javascript can be a particularly opaque language with some of its newer syntactic sugar. It’s always a slightly foreign language to me (my primary language is Swift); however, the more languages you’re exposed to, the easier it is to pick something up.

**Comment by jasonsnell** [comment]
yeah, this is such a touchy thing.. I do love the idea of stashing a default somewhere (and I have no idea how to do stuff like that, but if you would like to try it that would be awesome @lickel ) because that makes everything go faster. I feel like most people will want it around their house anyway. And then we could check periodically for location and just fall back to the stashed default if we can't update it.

It's a cool feature but if it destroys the stability of the widget it's not worth doing IMO... :-( So I hope we can find a compromise.

**Comment by lickel** [comment]
Yup, that's exactly what I was thinking as well. And, I'm not concerned about the stability at all; it should be perfectly safe to do this.

**Comment by jasonsnell** [comment]
Operation Location continues!

BTW a friend at Apple writes that he's spread the widget around inside Apple, which is fun.

**Comment by jasonsnell** [comment]
An interesting take from Jon Sadka:

https://gist.github.com/jonsadka/503b82e5aa7fd522831a03a32cd4f2a7
